In [1]:
import pandas as pd

In [2]:
ratings_data = pd.read_json("raw/renttherunway_final_data.json", lines=True)

In [3]:
ratings_data.head()

,fit,user_id,bust size,item_id,weight,rating,rented for,review_text,body type,review_summary,category,height,size,age,review_date
0,fit,420272,34d,2260466,137lbs,10.0,vacation,An adorable romper! Belt and zipper were a lit...,hourglass,So many compliments!,romper,"5' 8""",14,28.0,"April 20, 2016"
1,fit,273551,34b,153475,132lbs,10.0,other,I rented this dress for a photo shoot. The the...,straight & narrow,I felt so glamourous!!!,gown,"5' 6""",12,36.0,"June 18, 2013"
2,fit,360448,NaN,1063761,NaN,10.0,party,This hugged in all the right places! It was a ...,NaN,It was a great time to celebrate the (almost) ...,sheath,"5' 4""",4,116.0,"December 14, 2015"
3,fit,909926,34c,126335,135lbs,8.0,formal affair,I rented this for my company's black tie award...,pear,Dress arrived on time and in perfect condition.,dress,"5' 5""",8,34.0,"February 12, 2014"
4,fit,151944,34b,616682,145lbs,10.0,wedding,I have always been petite in my upper body and...,athletic,Was in love with this dress !!!,gown,"5' 9""",12,27.0,"September 26, 2016"

In [4]:
# convert user and item ids to user and item index (from 0 to n: the number of users/items)

uid_to_uidx = dict()
iid_to_iidx = dict()

# user and item index counter
uidx_cnt = 0
iidx_cnt = 0

for eachsample in ratings_data.itertuples(index=True):
    # users index
    if eachsample.user_id not in uid_to_uidx.keys():
        uid_to_uidx[eachsample.user_id] = uidx_cnt
        uidx_cnt += 1

    # items index
    if eachsample.item_id not in iid_to_iidx.keys():
        iid_to_iidx[eachsample.item_id] = iidx_cnt
        iidx_cnt += 1

In [8]:
# to write the rating data using new indices
import math
dataset_data = open("ClothingFit_data.txt", 'w')

for eachsample in ratings_data.itertuples(index=True):
    try:
        if not math.isnan(eachsample.rating):
            dataset_data.write(f"{str(uid_to_uidx[eachsample.user_id])},{str(iid_to_iidx[eachsample.item_id])},{str(int(eachsample.rating))}\n")
    except:
        print(eachsample.rating)

dataset_data.close()

In [9]:
from collections import defaultdict

category_data = defaultdict(set)

for eachsample in ratings_data.itertuples(index=True):
    if eachsample.item_id in category_data.keys():
        category_data[eachsample.item_id].add(eachsample.category)
    else:
        category_data[eachsample.item_id] = {eachsample.category}

In [10]:
# to write the movie data using new indices

genre_data = open("ClothingFit_genre.txt", 'w')

for eachsample in ratings_data.itertuples(index=True):
    category_genre = ""
    if eachsample.item_id in iid_to_iidx.keys():
        categories = "|".join(category_data[eachsample.item_id])
        genre_data.write(f"{str(iid_to_iidx[eachsample.item_id])},{categories}\n")

genre_data.close()